apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluxchat

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - backend/api-gateway.yaml
  - backend/auth-service.yaml
  - backend/user-service.yaml
  - backend/chat-service.yaml
  - backend/message-service.yaml
  - backend/websocket-service.yaml
  - backend/notification-service.yaml
  - frontend/frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: fluxchat-platform
      app.kubernetes.io/managed-by: kustomize

