apiVersion: v1
kind: Secret
metadata:
  name: fluxchat-secrets
  namespace: fluxchat
  labels:
    app.kubernetes.io/name: fluxchat-secrets
    app.kubernetes.io/part-of: fluxchat-platform
type: Opaque
stringData:
  # Replace values with production secrets or integrate with Vault / AWS Secrets Manager / SealedSecrets
  MONGODB_URL: "mongodb+srv://<db_user>:<db_password>@cluster.mongodb.net/?retryWrites=true&w=majority&appName=FluxChat"
  JWT_SECRET: "PRODUCTION_ENTERPRISE_JWT_SECRET_KEY_MUST_BE_AT_LEAST_64_CHARACTERS_LONG"
  TWOFACTOR_API_KEY: "2factor-production-api-key-placeholder"
  REDIS_PASSWORD: ""
